# Generated by Django 4.2.5 on 2023-09-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='package_images/')),
                ('place', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('person', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detail', models.TextField()),
            ],
        ),
    ]
