# Generated by Django 4.2.5 on 2023-09-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_packagedetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackageDetails',
        ),
    ]
