# Generated by Django 4.2.5 on 2023-09-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_slide_delete_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
