# Generated by Django 4.2.5 on 2023-09-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_delete_slide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='description',
            new_name='description_1',
        ),
        migrations.AddField(
            model_name='about',
            name='description_2',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
    ]
